In [1]:
%matplotlib widget
from essential_func import *
qgrid2 = np.hstack([np.arange(0.005, 0.0499, 0.001), np.arange(0.05, 0.099, 0.002), np.arange(0.1, 3.2, 0.005)])

In [7]:
############### -------- configure patch size and copy the pathces tuplte to the next cell for computing 1-d averaging for all frames ------------- ###################
frame = 100
file = '2016_B8c_masked.h5'
patches = patches = [


                    ]
mica_patching(file, frame, patches, qgrid2)

frame information extraction completes with _SAXS shape (1, 1043, 981) _WAXS shape (1, 1043, 981)...
Circular averaging starts now ... 
2016_B8c_masked_100.h5 total 1-d averaging time 0.4481034580000198 seconds


/Users/bashit.a/Documents/Alzheimer/Dec-15/py4xs/data2d.py:350: RuntimeWarning: invalid value encountered in sqrt
  dI = np.sqrt(Iq2-Iq*Iq)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [5]:
# 1-d averaging after patches for one file
### spec
source_file = "2016_B8c.h5"
patches = [
                             [[800, 0], [980, 150]],
                             [[165, 0], [365, 140]],
                             [[595, 215], [625, 240]],
                             [[0, 580], [40, 620]],
                             [[605, 890], [655, 920]],
                             [[0, 910], [75, 965]],
                             [[290, 385], [340, 405]],
                             [[900, 700], [950, 740]]
          ]

### computation
masked_file = circ_avg_from_patches(source_file, qgrid2, patches)
print(f'Successfully created {file} ---> {masked_file}')

2016_B8c_masked.h5 is being created in /Users/bashit.a/Documents/Alzheimer/Dec-15 ...
2016_B8c_masked.h5 copy is done
2016_B8c_masked.h5 Loading data into a numpy array started 
2016_B8c_masked.h5 Loading data into a numpy array finished in 17.170424957999998 seconds
2016_B8c_masked.h5 Patching Started 
2016_B8c_masked.h5 Patching Finished
2016_B8c_masked.h5 patched pilW2_image dataset creation staring ... 
2016_B8c_masked.h5 patched pilW2_image dataset creation finished in 25.279902500000006 seconds
Circular averaging starts now ... 
data received: sn=2016_B8c, fr1=0
data received: sn=2016_B8c, fr1=160
data received: sn=2016_B8c, fr1=320
data received: sn=2016_B8c, fr1=480
data received: sn=2016_B8c, fr1=640
data received: sn=2016_B8c, fr1=800
data received: sn=2016_B8c, fr1=960
data received: sn=2016_B8c, fr1=1120
2016_B8c_masked.h5 total 1-d averaging time 136.16326216700003 seconds
Successfully created 1934_SNa_masked.h5 ---> 2016_B8c_masked.h5


In [4]:
## patching information retrival from _masked.h5 file
from essential_func import *

#specs
file = "1934_SNa_masked.h5"

# computation
try: patches = get_patch_attributes(f'{file}'); print(patches)
except: print(f'{file} does not have patches information on the processed folder')

[[[800, 0], 180, 150, 'red'], [[245, 0], 140, 130, 'green'], [[0, 590], 40, 25, 'orange'], [[300, 720], 45, 30, 'black'], [[625, 895], 40, 35, 'yellow'], [[15, 930], 60, 40, 'brown'], [[900, 705], 50, 40, 'pink']]


In [19]:
### check config.json file integrity
from essential_func import *
No_error_no_prb = get_json_str_data('config-dec-15.json');

In [ ]:
# 1-d averaging after patches for ALL files in the current directory

data = get_json_str_data("config-dec-15.json")
### do masking and 1-d averaging (Lin Yang's code by BNL used here for 1-d averaging)
files = []
for file in data['files']:
    source_file , patches = file['name'], file['patches']
    try: masked_file = circ_avg_from_patches(source_file, qgrid2, patches)
    except: continue
    files.append((source_file, masked_file))

print(f'Successfully created (source file, masked file) \n\n')
[print(s, '--->' ,t) for s,t in files]
pass

DID not PATCH 1934_B8_masked.h5 already exists - did not copy, 
1-D Averaging is NOT performed as 1934_B8_masked.h5 already exist 
TO do patching on 1934_B8_masked.h5 delete the file first manually and run this cell again
1934_SN_masked.h5 is being created in /Users/bashit.a/Documents/Alzheimer/Dec-15 ...
1934_SN_masked.h5 copy is done
1934_SN_masked.h5 Loading data into a numpy array started 
1934_SN_masked.h5 Loading data into a numpy array finished in 71.519835875 seconds
1934_SN_masked.h5 Patching Started 
1934_SN_masked.h5 Patching Finished
1934_SN_masked.h5 patched pilW2_image dataset creation staring ... 
1934_SN_masked.h5 patched pilW2_image dataset creation finished in 117.57385520800001 seconds
Circular averaging starts now ... 
data received: sn=1934_SN, fr1=0
data received: sn=1934_SN, fr1=620
data received: sn=1934_SN, fr1=1240
data received: sn=1934_SN, fr1=1860
data received: sn=1934_SN, fr1=2480
data received: sn=1934_SN, fr1=3100
data received: sn=1934_SN, fr1=3720
dat

In [4]:
### 1d circularly averaged data for masked file 
%matplotlib widget
from essential_func import *
import ipywidgets   # from IPython.display import display; display(amp)

# specs  
masked_file = "1934_SN_masked.h5"   
scattering = '_WAXS2'

# semi-specs
file = masked_file 
qgrid2 = np.hstack([np.arange(0.005, 0.0499, 0.001), np.arange(0.05, 0.099, 0.002), np.arange(0.1, 3.2, 0.005)])

# computation
Iq = read_Iq(file, scattering)    
Width, Height = width_height(file)    
n_patterns = Width*Height 

f,ax = plt.subplots()
def update_plot(frame):
    ax.clear()
    ax.set_yscale('log')
    ax.plot(qgrid2, (Iq[frame]), label = f'{scattering} {frame}')

frame = ipywidgets.IntSlider(min=0, max=n_patterns-1, value=0, description = "Frame")
ipywidgets.interactive(update_plot, frame=frame)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

interactive(children=(IntSlider(value=0, description='Frame', max=4960), Output()), _dom_classes=('widget-inte…

In [5]:
### show heat map for any file
%matplotlib widget    
from essential_func import *

file = '2048_B8.h5'
#file = masked_file    
scatterings = ('_SAXS', '_WAXS2')

#plot_one_heat_maps(file, scatterings)
f = plot_heat_map_from_file(file, qgrid2, scatterings = scatterings)
print('Task Finished. Figure Number = ' , f.number)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
Task Finished. Figure Number =  1


In [6]:
################# --------- Find Q range to plot heat maps --------- #################
%matplotlib widget
from essential_func import *
import ipywidgets         # from IPython.display import display; display(amp)
from ipywidgets import fixed


# semi-specs
qgrid2 = np.hstack([np.arange(0.005, 0.0499, 0.001), np.arange(0.05, 0.099, 0.002), np.arange(0.1, 3.2, 0.005)])

### q_low, q_high, q_low - idx[2] and q_high + idx[2] for poly fit, number of points
indices = ((0.115, 0.16, 13,   48, '_SAXS' , 'bumpy'),      # 72, 81
           (1.48,  1.57, 10, 4.15, '_WAXS2', 'paraffin'),   # 345, 355
           (1.30,  1.38, 10,  4.7, '_WAXS2', 'amyloid'),    # 309, 323
           (1.89,  1.93,  7,  3.2, '_WAXS2', 'mica')        # 427, 433
          )

## polyhit with heatmap from drop down list
files = cwd_files_type_search('.h5')
dropdown = ipywidgets.Dropdown(options=files, value = files[0],description='File : ', disabled=False)
ipywidgets.interact(file_polyfit_heatmap_plot, file = dropdown, indices = fixed(indices), qgrid2 = fixed(qgrid2))


## polyhit with heatmap for one file
# file = '2048_B8.h5'
# file_polyfit_heatmap_plot(file, indices, qgrid2)

interactive(children=(Dropdown(description='File : ', options=('1934_B8.h5', '1934_B8_masked.h5', '1934_SN.h5'…

<function essential_func.file_polyfit_heatmap_plot(file, indices, qgrid2)>

In [2]:
### Merge all PDFs in the directory specified
### you can put all your pdfs that you want to merge to the PDF folder
from essential_func import *
pdfs_merging(directory = '/PDF', output = 'result.pdf')

Current location /Users/bashit.a/Documents/Alzheimer/Dec-15
Changing to /Users/bashit.a/Documents/Alzheimer/Dec-15//PDF directory 
result.pdf file written successfully
Back to root directory  /Users/bashit.a/Documents/Alzheimer/Dec-15


In [8]:
%matplotlib widget
from essential_func import *
from py4xs.hdf import h5xs
import os
from py4xs.slnxs import trans_mode

print(f'{os.getcwd()}')

# specs
# file = '1934_SN_masked.h5'  
# frames = (4518, 3687, 3045)     # amyloid, mica, dark  ---> frames can be choosen from SAXS heat map

file = '2048_B8_masked.h5'
frames = (2080, 1358, 2223, )     # amyloid, mica, dark
show_eb = False                  # show errorbar in the plot


## semi-spec
qgrid2 = np.hstack([np.arange(0.005, 0.0499, 0.001), np.arange(0.05, 0.099, 0.002), np.arange(0.1, 3.2, 0.005)])

# creating objects
dt  = h5xs(f'{file}', transField="em2_sum_all_mean_value")
sn = h5_top_group(file)
dt.load_d1s(sn=sn)

## heat map from file
scatterings = ('_SAXS', '_WAXS2')
f = plot_heat_map_from_file(file, qgrid2, scatterings = scatterings)

### 1-d plot for bright, moderate and dark frames
scatterings = ('_SAXS',          '_WAXS2',        'merged',    )
colors =      (('r','b','g'), ('r','b','g'), ('r+','bo','g--'),)
f, axs = plt.subplots(1, 3, figsize=(15,5), num=f'{file}')
xscale = 'linear'
yscale = 'log'

for i, (scattering, color) in enumerate(zip(scatterings,colors)):
    axs[i].plot(dt.qgrid, dt.d1s[sn][scattering][frames[0]].data, color[0], label = f'bright {frames[0]}')
    axs[i].plot(dt.qgrid, dt.d1s[sn][scattering][frames[1]].data, color[1], label = f'moderate {frames[1]}')
    axs[i].plot(dt.qgrid, dt.d1s[sn][scattering][frames[2]].data, color[2], label = f'dark {frames[2]}')
    axs[i].set(title = f'{scattering} {file}', xscale= xscale, yscale= yscale)
    axs[i].legend()

## background correction calculations
sc_factor=1.

dset = dt.d1s[sn][scattering][frames[0]]
dbak = dt.d1s[sn][scattering][frames[2]]

dt.set_trans(transMode=trans_mode.external)
sc  = dset.trans / dbak.trans
print(f'Scaling factor, {dset.trans}/{dbak.trans} = {sc}')
Iq  = dset.data - dbak.data * sc * sc_factor
dI  = dset.err  + dbak.err * sc * sc_factor
idx = (dset.data > 0) & (dbak.data > 0)

## plotting settings
f, axs = plt.subplots(1,2,figsize=(16,4))
plt.subplots_adjust(bottom=0.15)

axs[0].plot(dbak.qgrid[idx], dset.data[idx], color[0], label = f'bright {frames[0]}')
axs[0].plot(dbak.qgrid[idx], dbak.data[idx], color[2], label = f'dark-bcg {frames[2]}')

if show_eb:
    axs[0].errorbar(dbak.qgrid[idx], Iq[idx], dI[idx])
    axs[1].errorbar(dbak.qgrid[idx], Iq[idx], dI[idx], label = f'{frames[0]} bcor')
else:
    axs[0].plot(dbak.qgrid[idx], Iq[idx], label = 'bcor')
    axs[1].plot(dbak.qgrid[idx], Iq[idx], label = f'{frames[0]} bcor')


axs[0].set(xlabel = "$q (\AA^{-1})$", ylabel = "$I$", title = f'Background correction {file} errorbar = {show_eb}', xscale = xscale, yscale = yscale, )
axs[1].set(xscale = xscale, yscale = yscale, title = f'Final Background Subtracted {file} errorbar = {show_eb}' , )
axs[0].legend()
axs[1].legend()

/Users/bashit.a/Documents/Alzheimer/Dec-15


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Scaling factor, 45131.328/45333.208 = 0.9955467523939625


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [2]:
# pdf generation package all files in the cwd
%matplotlib widget
from essential_func import *

### heat plots for all files in a folder
scatterings = ('_SAXS', '_WAXS2')
qgrid2 = np.hstack([np.arange(0.005, 0.0499, 0.001), np.arange(0.05, 0.099, 0.002), np.arange(0.1, 3.2, 0.005)])

plot_all_heat_maps_cwd('output.pdf', qgrid2, scatterings)

Loading file 1934_B8.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
1934_B8.h5 Task Finished. Figure Number =  1
Loading file 1934_SN.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
1934_SN.h5 Task Finished. Figure Number =  2
Loading file 1934_SNa.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
1934_SNa.h5 Task Finished. Figure Number =  3
Loading file 1943_B1.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
1943_B1.h5 Task Finished. Figure Number =  4
Loading file 1943_B1a.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
1943_B1a.h5 Task Finished. Figure Number =  5
Loading file 2016_B8.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2016_B8.h5 Task Finished. Figure Number =  6
Loading file 2016_B8a.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2016_B8a.h5 Task Finished. Figure Number =  7
Loading file 2016_B8b.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2016_B8b.h5 Task Finished. Figure Number =  8
Loading file 2016_B8c.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2016_B8c.h5 Task Finished. Figure Number =  9
Loading file 2047_B1.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2047_B1.h5 Task Finished. Figure Number =  10
Loading file 2047_B1a.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2047_B1a.h5 Task Finished. Figure Number =  11
Loading file 2048_B16.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2048_B16.h5 Task Finished. Figure Number =  12
Loading file 2048_B16a.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2048_B16a.h5 Task Finished. Figure Number =  13
Loading file 2048_B16b.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2048_B16b.h5 Task Finished. Figure Number =  14
Loading file 2048_B6.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2048_B6.h5 Task Finished. Figure Number =  15
Loading file 2048_B8.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2048_B8.h5 Task Finished. Figure Number =  16
Loading file 2048_B8_masked_test.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
2048_B8_masked_test.h5 Task Finished. Figure Number =  17
Loading file exp.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Loading file mica.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

low valid idx = 2, low valid Q = 0.007, high valid idx = 124 , high valid Q = 0.370
low valid idx = 109, low valid Q = 0.295, high valid idx = 578 , high valid Q = 2.640
mica.h5 Task Finished. Figure Number =  19
Loading file std.h5


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

PDF creation Finished


In [10]:
# import pylab as plt
# from matplotlib.widgets import Cursor
# import numpy as np
# x,  y  = np.random.randn(2,10)
# print(x.shape, y.shape)
# f, axs = plt.subplots(1,2)
# axs[0].plot(x,y,'o')
# axs[1].plot(x,y,'o')

# cursor = Cursor(axs[0],
#                 horizOn = True,
#                 vertOn = True,
#                 color= 'green',
#                 linewidth = 1
#                )
# pos = []
# def onclick(event):
#     x1, y1 = event.xdata, event.ydata
#     pos.append((x1,y1))
#     print(x1,y1)

# f.canvas.mpl_connect('button_press_event',  onclick)
#print(pos)

# def hover(event):
#     if event.inaxes != ax:
#         return
#     info = 'x={:.2f}, y={:.2f}'.format(event.xdata, event.ydata)
#     ax.format_coord = lambda x, y: info
# cid = ax.figure.canvas.mpl_connect("motion_notify_event", hover)

# ratio = Height/Width
# xleft, xright = ax.get_xlim()
# ybottom, ytop = ax.get_ylim()
# abs((xright-xleft)/(ybottom-ytop))*ratio
# 1/ax.get_data_ratio()

In [11]:
### -------- py4xs version --------

%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
# Fixing random state for reproducibility
np.random.seed(19680801)

Height = 3
Width = 6
X = np.random.randint(1, 20, size=(Height, Width))

fig, ax = plt.subplots()
ax.imshow(X, interpolation = 'none', origin='upper', extent=[0,Width,0,Height],aspect='equal')

def snaking( Width, Height, X=None,):
    if X is None:
        X_coor = np.arange(Height*Width).reshape(Height,Width)
    else:
        X_coor = X
    output = np.zeros_like(X_coor)           # 
    temp = np.flipud(X_coor)                # flipud matrix
    idx_odd = np.arange(1,Height,2)                # Get odd indices to fliplr
    output[idx_odd,:]  = np.fliplr(temp[idx_odd])   # flipping odd indices
    idx_even = np.arange(0,Height,2)               # Get odd indices to leave to as it is
    output[idx_even,:] = temp[idx_even]             # leaving as it is
    return output

frame_cor = snaking(Width, Height)
diff_patterns = snaking(Width, Height, X)

print('Diff_patt_idx_before snaking: \n', np.arange(Height*Width).reshape(Height,Width), '\n\n',
      'Diff_patt_before snaking: \n', X, '\n\n', 
      'X,Y coordinates_after_snaking: \n', frame_cor, '\n\n',
      'Diff_patt_after snaking: \n', diff_patterns, '\n\n',)

numrows, numcols = X.shape
def format_coord(x, y):
    col = int(x)
    row = int(y)
    if 0 <= col < numcols and 0 <= row < numrows:
        z = np.flipud(frame_cor)[row, col]
        return 'x=%1.4f, y=%1.4f, FRAME=%d' % (x, y, z)
    else:
        return 'x=%1.4f, y=%1.4f' % (x, y)

ax.format_coord = format_coord

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Diff_patt_idx_before snaking: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

 Diff_patt_before snaking: 
 [[13 14  7  3  3  4]
 [18  5 11 19 12  9]
 [ 6 12  4  6 17 10]] 

 X,Y coordinates_after_snaking: 
 [[12 13 14 15 16 17]
 [11 10  9  8  7  6]
 [ 0  1  2  3  4  5]] 

 Diff_patt_after snaking: 
 [[ 6 12  4  6 17 10]
 [ 9 12 19 11  5 18]
 [13 14  7  3  3  4]] 




In [ ]:
# --------- template matching purposes -------------


# plot zoomed patch figure
#plt.figure()
#pil_im = img[0:150, 800:800+150]
#plt.imshow(pil_im, cmap = 'rainbow', ); 
#plt.show();

# --------- template matching -------------
# template_file = ''
# Cropped image of above dimension OPENCV to PIL_IMAGE
# https://stackoverflow.com/questions/43232813/convert-opencv-image-format-to-pil-image-format
# PIL to OpenCV
#pil_im = Image.fromarray(img_rgb)
#pil_im = pil_im.crop((left, top, right, bottom))
# load template and find height and width of the template shape (convert your BGR image to Gray image)
#template = pil_im
#h, w = template.shape[::]
# print(f'template width {w} Height {h}')
# print(np.min(template), np.max(template), np.min(img), np.max(img))
# print(f'templete {template.shape} type {type(template)} pil_im {img.shape} type {type(img)}')
#res = cv2.matchTemplate(img_rgb, template, cv2.TM_CCOEFF)

In [19]:
### Finding Radius of gyration
from py4xs.hdf import h5xs,h5exp,lsh5,proc_d1merge
from py4xs.data2d import Data2d
from py4xs.slnxs import trans_mode
import numpy as np
import pylab as plt
import warnings,json

warnings.filterwarnings('ignore')

dt0  = h5xs("mica.h5", transField="em2_sum_all_mean_value")
dt  = h5xs("2048_B8.h5", transField="em2_sum_all_mean_value")

dt.load_d1s()
dt0.load_d1s()

dt.set_trans(transMode=trans_mode.external)
dt0.set_trans(transMode=trans_mode.external)

print(dt.d1s['2048_B8']['merged'][2080].trans)
print(dt0.d1s['mica']['merged'][10].trans)
#print(dt.d1s['2048_B8']['merged'][2080].overlaps)
#dt0.d1s['mica']['merged'][10].plot()

45131.328
45639.848


In [20]:
td = np.vstack((dt.qgrid, dt.d1s['2048_B8']['merged'][2080].data))
qs = 0.007
qe = 10
rg = 15
# td = td[:, td[0, :] >= qs]     # find td for  greater than q=0.007
# td = td[:, td[0, :] <= qe]     # find td for smaller than q=1.3/1.5=0.086
# td[0, :] = td[0, :] * td[0, :]
# td[1, :] = np.log(td[1, :])
# rg, i0 = np.polyfit(td[0, :], td[1, :], 1)

In [21]:
from numpy.polynomial import polynomial as P
cnt = 0
while cnt < 10:
    if qe > 1.3/rg and 1.3/rg > qs+0.004: 
        qe = 1.3/rg
    td = np.vstack((dt.qgrid, dt.d1s['2048_B8']['merged'][2080].data))
    td = td[:, td[0, :] >= qs]     # find td for  greater than q=0.007
    td = td[:, td[0, :] <= qe]     # find td for smaller than q=1.3/1.5=0.086
    td[0, :] = td[0, :] * td[0, :]
    td[1, :] = np.log(td[1, :])
    rg, i0 = np.polyfit(td[0, :], td[1, :], 1)
    i0 = np.exp(i0)
    
    print(cnt, qe, rg, i0)
    
    if rg<0:
        rg = np.sqrt(-rg * 3.)
    else:
        rg = 1e-6   # 
        print("likely strong inter-particle interaction ...")
        break
    cnt += 1
print(rg)

0 0.08666666666666667 -831.264016704801 20.377926211495332
1 0.026032341584365102 -6234.912831830037 281.9576616244667
2 0.026032341584365102 -6234.912831830037 281.9576616244667
3 0.026032341584365102 -6234.912831830037 281.9576616244667
4 0.026032341584365102 -6234.912831830037 281.9576616244667
5 0.026032341584365102 -6234.912831830037 281.9576616244667
6 0.026032341584365102 -6234.912831830037 281.9576616244667
7 0.026032341584365102 -6234.912831830037 281.9576616244667
8 0.026032341584365102 -6234.912831830037 281.9576616244667
9 0.026032341584365102 -6234.912831830037 281.9576616244667
136.76526786977064


In [72]:
%matplotlib widget
qmax = 5;
dmax=200.;

if dt.qgrid[-1] < qmax: 
    qmax = dt.qgrid[-1]

tqgrid = np.arange(0, qmax, qmax / len(dt.qgrid))
tint = np.interp(tqgrid, dt.qgrid, dt.d1s['2048_B8']['merged'][2080].data)
print(tint.shape)
tint[tqgrid * rg < 1.] = i0 * np.exp(-(tqgrid[tqgrid * rg < 1.] * rg) ** 2 / 3.)
#print(tint)

# tint -= tint[-10:].sum()/10
# Hanning window for reducing fringes in p(r)
tw = np.hanning(2 * len(tqgrid) + 1)[len(tqgrid):-1]

# plotting hanning window
tmp = np.hanning(2 * len(tqgrid) + 1)
#plt.plot(np.arange(0,len(tint[tqgrid * rg < 1.])), tint[tqgrid * rg < 1.])
#plt.yscale('log')
tint *= tw
#plt.show()

trgrid = np.arange(0, dmax, 1.)
kern = np.asmatrix([[rj ** 2 * np.sinc(qi * rj / np.pi) for rj in trgrid] for qi in tqgrid])
tt = np.asmatrix(tint * tqgrid ** 2).T
tpr = np.reshape(np.array((kern.T * tt).T), len(trgrid))
tpr /= tpr.sum()
print(tpr.shape)

(690,)
(200,)


In [39]:
tqgrid = np.arange(0, qmax, qmax / len(dt.qgrid))
tint = np.interp(tqgrid, dt.qgrid, dt.d1s['2048_B8']['merged'][2080].data)
tqgrid[0:10]

array([0.        , 0.00463043, 0.00926087, 0.0138913 , 0.01852174,
       0.02315217, 0.02778261, 0.03241304, 0.03704348, 0.04167391])

In [40]:
tint[0:10]

array([  0.        ,   0.        , 226.1832685 ,  59.61769605,
        22.97810842,  11.09743954,   6.12499604,   3.7438397 ,
         2.53240456,   1.68923436])

In [41]:
dt.d1s['2048_B8']['merged'][2080].data[0:10]

array([  0.        ,   0.        , 537.48069252, 361.86465338,
       245.04076906, 172.75368358, 126.1101004 ,  95.09058784,
        74.10259362,  57.85124512])