In [1]:
%matplotlib widget

In [4]:
from py4xs.hdf import h5xs,h5exp,lsh5,proc_d1merge
from py4xs.data2d import Data2d
from py4xs.slnxs import trans_mode
import numpy as np
import pylab as plt
import warnings,json
import os

warnings.filterwarnings('ignore')

## create the h5xs object for azimuthal average first
assign the detector configuration and q-grid:

  `dt0  = h5xs("mica.h5", [de.detectors, qgrid2])`

then do the batch processing:

  `dt0.load_data()   `

In general this is going to take a lot of memory. For larger datasets, run load_data(N=16) to avoid crash. This may not work on you laptop if you don't have enough memory. This step is time consuming. I recommend running this for all h5 files first. The data1d objects created from azimuthal average will be saved back to the h5 file.
  
## recreating the h5xs object for further processing

Re-create the data1d objects from information saved in the h5 fil is a lot faster and does not require a lot of memory.

  `dt0 = h5xs("mica.h5", transField="em2_sum_all_mean_value")` <br>
  `dt0.load_d1s()`

Then populate the *trans* attribute for all data1d objects based on the specified transfield. When calling bkg_cor() later for background subtraction, this *trans* value should be accounted for (data scaled) automatically.

  `dt0.set_trans(transMode=trans_mode.external)`

In [5]:
os.chdir('/Users/bashit.a/Documents/Alzheimer/Dec-2020')      # location where your h5 and exp file are    Mar-24/BNL-Data/
dt0  = h5xs("mica.h5", transField="em2_sum_all_mean_value")
dt  = h5xs("2048_B8_masked.h5", transField="em2_sum_all_mean_value")

dt.load_d1s()
dt0.load_d1s()

dt.set_trans(transMode=trans_mode.external)
dt0.set_trans(transMode=trans_mode.external)

In [6]:
%matplotlib widget
(i0, rg, fit_range) = dt.d1s['2048_B8']['merged'][2080].plot_Guinier();
print(rg)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

136.76526786977064


In [7]:
%matplotlib widget
f,ax = plt.subplots();
dt.d1s['2048_B8']['merged'][2080].plot_pr(i0,rg, dmax = 800, ax=ax);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [10]:
print(dt.d1s['2048_B8']['merged'][2080].trans)
print(dt0.d1s['mica']['merged'][10].trans)
print(dt.d1s['2048_B8']['merged'][2080].overlaps)
#dt0.d1s['mica']['merged'][10].plot()
dt.d1s['2048_B8']['merged'][2080].plot()

45131.328
45639.848
[]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [25]:
dt.d1s['2048_B8']['merged'][2223].data

array([0.00000000e+00, 0.00000000e+00, 9.82849867e+00, 6.45468488e+00,
       4.46113370e+00, 3.08046540e+00, 2.15617222e+00, 1.52618740e+00,
       1.20809589e+00, 1.00967285e+00, 7.66016009e-01, 6.47855032e-01,
       5.45870961e-01, 4.56567354e-01, 3.69312148e-01, 3.74493540e-01,
       2.83155068e-01, 2.68243314e-01, 2.29501601e-01, 1.90910359e-01,
       1.73984423e-01, 1.49968235e-01, 2.01492931e-01, 1.82893342e-01,
       1.46958039e-01, 1.63899838e-01, 1.59392855e-01, 1.46368997e-01,
       1.17106206e-01, 1.34797025e-01, 1.21516141e-01, 1.21660631e-01,
       1.23521731e-01, 1.08994662e-01, 1.05523566e-01, 1.00924503e-01,
       1.02654461e-01, 1.16118315e-01, 1.04862463e-01, 1.15001720e-01,
       1.08004264e-01, 9.63038154e-02, 1.09466217e-01, 9.35881013e-02,
       1.03713216e-01, 9.94110874e-02, 9.39930645e-02, 1.00423459e-01,
       9.95888678e-02, 9.52346572e-02, 9.11492838e-02, 9.04704394e-02,
       9.39775762e-02, 9.51866195e-02, 9.26253231e-02, 9.54434228e-02,
      

In [3]:
# scan header
#header['snaking']

dt  = h5xs("2048_B8.h5", transField="em2_sum_all_mean_value")
#print(dt['2048_B8'].attrs['start'])
header = json.loads(dt.fh5[dt.samples[0]].attrs['start'])
Height, Width = header['shape']
#print(header['shape'])
print(Width, Height)
header

61 81


{'uid': '3c321f80-c026-4776-953a-37ffbe730b8f',
 'time': 1608093495.3446026,
 'proc_path': '/nsls2/xf16id1/experiments/2020-3/308074/306605/',
 'subdir': None,
 'CRL': {'state': [1, 1, 1, 0, 1, 1, 1, 0, 0],
  'x1': -0.17103125,
  'y1': 6.45796875,
  'x2': 0.12896875000000002,
  'z': 650.0000000000001},
 'det_pos': {'saxs': {'x': 454.09625,
   'y': 755.15509375,
   'z': 499.88945000000217},
  'waxs1': {'x': -2.29, 'y': -1.1600660000000005, 'z': 846.0620595},
  'waxs2': {'x': 60.000043299999994,
   'y': -145.0000521,
   'z': 34.99999759999997}},
 'BPM': {'stage position': {'x': 6.104998999999999, 'y': -0.08199999999999999},
  'beam position': {'x': 0.004462539485698518, 'y': -0.011241976628202352}},
 'run_id': '306605',
 'group': 'lix',
 'owner': 'LY',
 'optics': {'wbm_y': 0.32030000000000003,
  'wbm_pitch': 1.7778301999999995,
  'dcm_y2': -16.5094,
  'mono_x': 0.004,
  'hfm_x1': -0.1525,
  'hfm_x2': -3.1925,
  'vfm_y1': -0.7305,
  'vfm_y2': 2.4395000000000002},
 'proposal_id': '308074',

In [4]:
f, (ax1, ax2, ax3) = plt.subplots(1,3,figsize=(10,6))

xpos = dt.fh5[f"{dt.samples[0]}/primary/data/ss_sx"][...]
ypos = dt.fh5[f"{dt.samples[0]}/primary/data/ss_sz"][...]

ax1.plot(xpos, np.arange(len(xpos)) )
ax2.plot(np.arange(len(xpos)), ypos )
ax3.plot(xpos, ypos)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [19]:
d1 = dt.d1s['2048_B8']['merged'][2080].bkg_cor(dt.d1s['2048_B8']['merged'][2223], plot_data=False, debug=True, show_eb=False )
#d1.plot()
print(d1.comments)

background subtraction: 2048_B8mergedf02080 - 2048_B8mergedf02223
using scaling factor of 0.995547


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# transmitted beam intensity is defined externally: 45131.328000: 45131.328000 
# background subtraction using the following set, scaled by 0.995547 (trans):
## transmitted beam intensity is defined externally: 45333.208000: 45333.208000 



In [1]:
import copy

def unpack_d1(data, qgrid, label, trans_value):
    """ utility function to creat a Data1d object from hdf dataset
        sepatately given data[intensity and error], qgrid, label, and trans  
        works for a dataset that include a list of 1d data as well
        transMode is set to trans_mode.external
    """
    #print('data shape', data.shape)
    if len(data.shape)>2:
        if np.isscalar(trans_value): # this should only happen when intentionally setting trans to 0  ### always true for our case
            trans_value = np.zeros(len(data))    # 3721 zeros 
        return [unpack_d1(d, qgrid, label+("f%05d" % i), t) for i,(d,t) in enumerate(zip(data,trans_value))]   # d --> (2,690) t--> 0 data --> (3721,2,690) trans_value --> 3721,
        '''
        for i,(d,t) in enumerate(zip(data,trans_value)):
            unpack_d1(d, qgrid, label+("f%05d" % i), t)  
        '''
        # executes when data --> (2,690)
    else:
        ret = Data1d()
        ret.qgrid = qgrid
        ret.data = data[0]
        ret.err = data[1]
        ret.label = label
        ret.trans = trans_value
        ret.transMode = trans_mode.external
        return ret

def lsh5(hd, prefix='', top_only=False, silent=False):
    """ list the content of a HDF5 file
        
        hd: a handle returned by h5py.File()
        prefix: use to format the output when lsh5() is called recursively
        top_only: returns the names of the top-level groups
        silent: suppress printouts if True
    """
    if top_only:
        tp_grps = list(hd.keys())
        if not silent:
            print(tp_grps)
        return tp_grps
    for k in list(hd.keys()):
        print(prefix, k)
        if isinstance(hd[k], h5py.Group):
            print(list(hd[k].attrs.items()))
            lsh5(hd[k], prefix+"=")

            
font_size_list = ['xx-small', 'x-small', 'small', 'medium', 'large', 'x-large', 'xx-large']
def get_font_size(size_index):
    """ "medium" has size_index of 0
        the size_index is negative for smaller fonts and possitive for larger ones  
    """
    if size_index in font_size_list:
        i = font_size_list.index(size_index)
    else:
        i = int(size_index)+3
        if i<0:
            i = 0
        elif i>=len(font_size_list):
            i = len(font_size_list)-1
    return i-3,font_size_list[i]

class Data1d:
    def __init__(self, trandMode=None):
        self.comments = ""
        self.label = "data"
        self.overlaps = []
        self.raw_data = {}
        self.timestamp = None
        self.trans = 0
        
    def set_trans(self, trans=-1, ref_trans=-1, transMode=None, 
                  q_start=1.85, q_end=2.15, debug=False):
        """
        normalize intensity, from trans to ref_trans
        trans can be either from the beam center or water scattering
        this operation should be performed after SAXS/WAXS merge, because
        1. SAXS and WAXS should have the same trans
        2. if trans_mode is TRNAS_FROM_WAXS, the trans value needs to be calculated from WAXS data
        """
        if transMode is not None:
            self.transMode = transMode
        if self.transMode == trans_mode.from_waxs:
            # get trans for the near the maximum in the WAXS data
            # for solution scattering, hopefully this reflect the intensity of water scattering
            idx = (self.qgrid > q_start) & (self.qgrid < q_end)  # & (self.data>0.5*np.max(self.data))
            if len(self.qgrid[idx]) < 5:
                print("not enough data points under the water peak, consider using a different trans_mode.")
                #raise Exception()
            
            # trying to narrow down the peak range turns out to be a bad idea
            # the width then could vary between datasets, creating artificial fluctuation in trans 
            #idx1 = idx & (self.data >= 0.95*np.max(self.data[idx]))

            if (self.data[idx]<WAXS_THRESH).all() and debug!='quiet':
                print("the data points for trans calculation are below WAXS_THRESH: ", 
                      np.max(self.data[idx]), WAXS_THRESH)                
            self.trans = np.sum(self.data[idx])
            qavg = np.average(self.qgrid[idx])
            if self.trans<1.0:
                print('caluclated trans is %f, setting it artifically to WAXS_THRESH.' % self.trans)
                self.trans = WAXS_THRESH
            if debug==True:
                print("using data near the high q end (q~%f)" % qavg, end=' ')
            self.comments += "# transmitted beam intensity from WAXS (q~%.2f)" % qavg
        elif self.transMode == trans_mode.external:
            if trans > 0:
                self.comments += "# transmitted beam intensity is defined externally: %f"%trans
                self.trans = trans
            elif self.trans<0:
                print("trans_mode is TRANS_EXTERNAL but a valid trans value is not provided")
                raise Exception()
        else:
            raise Exception("invalid transmode: ", self.tMode)

        self.comments += ": %f \n" % self.trans
        if debug==True:
            print("trans for %s set to %f" % (self.label, self.trans))

        if ref_trans > 0:
            self.comments += "# scattering intensity normalized to ref_trans = %f \n" % ref_trans
            self.data *= ref_trans / self.trans
            self.err *= ref_trans / self.trans
            for ov in self.overlaps:
                ov['raw_data1'] *= ref_trans / self.trans
                ov['raw_data2'] *= ref_trans / self.trans
            self.trans = ref_trans
            if debug==True:
                print("normalized to %f" % ref_trans)

    
class h5xs():
    """ Scattering data in transmission geometry
        Transmitted beam intensity can be set either from the water peak (sol), or from intensity monitor.
        Data processing can be done either in series, or in parallel. Serial processing can be forced.
        
    """    
    def __init__(self, fn, exp_setup=None, transField='', save_d1=True):
        """ exp_setup: [detectors, qgrid]
            transField: the intensity monitor field packed by suitcase from databroker
            save_d1: save newly processed 1d data back to the h5 file
        """
        self.d1s = {}
        self.detectors = None
        self.samples = []
        self.attrs = {}
        # name of the dataset that contains transmitted beam intensity, e.g. em2_current1_mean_value
        self.transField = None  

        self.fn = fn
        self.save_d1 = save_d1
        self.fh5 = h5py.File(self.fn, "r+")   # file must exist
        if exp_setup==None:     # assume the h5 file will provide the detector config
            self.qgrid = self.read_detectors()
        else:
            self.detectors, self.qgrid = exp_setup
            self.save_detectors()
        self.list_samples(quiet=True)
        # find out what are the fields corresponding to the 2D detectors
        # at LiX there are two possibilities
        data_fields = list(self.fh5[self.samples[0]+'/primary/data'])
        self.det_name = None
        # these are the detectors that are present in the data
        d_dn = [d.extension for d in self.detectors]
        '''
        det_names = [{"_SAXS": "pil1M_image",
                      "_WAXS1": "pilW1_image",
                      "_WAXS2": "pilW2_image"}, 
                     {"_SAXS": "pil1M_ext_image",
                      "_WAXS1": "pilW1_ext_image",
                      "_WAXS2": "pilW2_ext_image"}]
        '''
        for det_name in det_names:
            for k in set(det_name.keys()).difference(d_dn):
                del det_name[k]
            if set(det_name.values()).issubset(data_fields):
                self.det_name = det_name
                break
        if self.det_name is None:
            print('fields in the h5 file: ', data_fields)
            raise Exception("Could not find the data corresponding to the detectors.")
        if transField=='':
            # "2," --> self.transField = '' and self.transMode = trans_mode.from_waxs
            if 'trans' in self.fh5.attrs:
                [v, self.transField] = self.fh5.attrs['trans'].split(',')
                self.transMode = trans_mode(int(v))
                return
            else:
                self.transMode = trans_mode.from_waxs
                self.transField = ''
        elif transField not in data_fields:
            print("invalid filed for transmitted intensity: ", transField)
            raise Exception()
        else:
            self.transField = transField
            self.transMode = trans_mode.external
        self.fh5.attrs['trans'] = ','.join([str(self.transMode.value), self.transField])  # "0,em2_sum_all_mean_value"
        self.fh5.flush()
            
    def save_detectors(self):
        dets_attr = [det.pack_dict() for det in self.detectors]
        self.fh5.attrs['detectors'] = json.dumps(dets_attr)
        self.fh5.attrs['qgrid'] = list(self.qgrid)
        self.fh5.flush()
    
    def read_detectors(self):
        dets_attr = self.fh5.attrs['detectors']
        qgrid = self.fh5.attrs['qgrid']
        self.detectors = [create_det_from_attrs(attrs) for attrs in json.loads(dets_attr)]  
        return np.asarray(qgrid)
    
    def list_samples(self, quiet=False):
        self.samples = lsh5(self.fh5, top_only=True, silent=True)
        if not quiet:
            print(self.samples)
    
    def load_d1s(self, sn=None):
        """ load the processed 1d data saved in the hdf5 file into memory 
            for each sample
                 attribute "selected": which raw data are included in average
                 attribute "sc_factor": scaling factor used for buffer subtraction
            raw data: from each detector, and 'merged'
            averaged data: averaged from multiple frames
            corrected data: subtracted for buffer scattering
            buffer data will be recreated based on buffer assignment 
        """        
        print(sn)
        if sn==None:
            self.list_samples(quiet=True)
            for sn in self.samples:
                print('Recursion is going to call now')
                self.load_d1s(sn)
                print(f'sm is {sn} and Recursion is returned')  
        
        fh5 = self.fh5
        if "processed" not in lsh5(fh5[sn], top_only=True, silent=True): 
            print('Hey no processed')
            return
        
        print('Attributes list in the constructor object', list(self.attrs.keys()))
        if sn not in list(self.attrs.keys()):
            self.d1s[sn] = {}
            self.attrs[sn] = {}
        grp = fh5[sn+'/processed']
        print('processed attrs', grp.attrs.keys())
        for k in list(grp.attrs.keys()):
            self.attrs[sn][k] = grp.attrs[k]   
        for k in lsh5(grp, top_only=True, silent=True):   # k is '_SAXS', '_WAXS2' and 'merged'
            print(f'{k} is executing')
            if 'trans' in grp[k].attrs.keys():
                tvs = grp[k].attrs['trans']
            else:
                tvs = 0
            #print(grp[k].shape)
            #print(len(grp[k]))
            self.d1s[sn][k] = unpack_d1(grp[k], self.qgrid, sn+k, tvs)
        print(f'Finally recursion call is completed sn is {sn}')
        
    def set_trans(self, sn=None, transMode=None, interpolate=False, gf_sigma=5):
        """ set the transmission values for the merged data
            the trans values directly from the raw data (water peak intensity or monitor counts)
            but this value is changed if the data is scaled
            the trans value for all processed 1d data are saved as attrubutes of the dataset
        """
        if transMode is not None:
            self.transMode = transMode
        if self.transMode==None:
            raise Exception("a valid transmited intensity mode must be specified.")

        if sn is None:
            samples = self.samples
        else:
            samples = [sn]

        for s in samples:
            if transMode==trans_mode.external:
                if self.transField in self.fh5[f'{s}/primary/data/']:
                    trans_data = self.fh5[f'{s}/primary/data/{self.transField}'][...]
                    ts = self.fh5[f'{s}/primary/timestamps/{self.transField}'][...]
                elif self.transField in self.fh5[f'{s}']:
                    trans_data = self.fh5[f'{s}/{self.transField}/data/{self.transField}'][...]
                    ts = self.fh5[f'{s}/{self.transField}/timestamps/{self.transField}'][...]
                else:
                    raise Exception(f"could not find transmission data from {self.transField}.")
            if interpolate:  ## smoothing really
                spl = UnivariateSpline(ts, gaussian_filter(trans_data, gf_sigma))
                ts0 = self.fh5[f'{s}/primary/timestamps/{list(self.det_name.values())[0]}'][...]
                trans_data = spl(ts0)

            # these are the datasets that needs updated trans values
            print('d1s keys ', self.d1s[s].keys())
            if 'merged' not in self.d1s[s].keys():
                continue
            t_values = []
            print('loop length ',len(self.d1s[s]['merged']))
            for i in range(len(self.d1s[s]['merged'])):
                if self.transMode==trans_mode.external:
                    self.d1s[s]['merged'][i].set_trans(trans_data[i], transMode=self.transMode)
                else:
                    self.d1s[s]['merged'][i].set_trans(transMode=self.transMode)
                t_values.append(self.d1s[s]['merged'][i].trans)
            if 'averaged' not in self.d1s[s].keys():
                continue
            self.d1s[s]['averaged'].trans = np.average(t_values)
            
    def bkg_cor(self, dbak, sc_factor=1., plot_data=False, ax=None, 
                inplace=False, check_overlap=False, show_eb=True, debug=False, fontsize='large'):
        """
        background subtraction
        """
        dset = None
        if inplace:
            dset = self
        else:
            dset = copy.deepcopy(self)
        i_fs = get_font_size(fontsize)[0]

        if debug==True:
            print("background subtraction: %s - %s" % (dset.label, dbak.label))
        if not (dbak.qgrid == dset.qgrid).all():
            print("background subtraction failed: qgrid mismatch")
            sys.exit()
        if dset.trans < 0 or dbak.trans <= 0:
            print("WARNING: trans value not assigned to data or background, assuming normalized intensity.")
            sc = 1.
        else:
            sc = dset.trans / dbak.trans

        # need to include raw data
        if plot_data:
            if ax is None:
                plt.figure()
                plt.subplots_adjust(bottom=0.15)
                ax = plt.gca()
            ax.set_xlabel("$q (\AA^{-1})$", fontsize=get_font_size(i_fs)[1])
            ax.set_ylabel("$I$", fontsize=get_font_size(i_fs)[1])
            ax.set_xscale('log')
            ax.set_yscale('log')
            ax.xaxis.set_tick_params(labelsize=get_font_size(i_fs-1)[1])
            ax.yaxis.set_tick_params(labelsize=get_font_size(i_fs-1)[1])
            idx = (dset.data > 0) & (dbak.data > 0)
            ax.plot(dset.qgrid[idx], dset.data[idx], label=self.label)
            ax.plot(dbak.qgrid[idx], dbak.data[idx], label=dbak.label)
            ax.plot(dbak.qgrid[idx], dbak.data[idx] * sc * sc_factor, label=dbak.label + ", scaled")

        if len(dset.overlaps) != len(dbak.overlaps):
            if check_overlap:
                raise Exception("Background subtraction failed: overlaps mismatch.")
        else:
            for i in range(len(dset.overlaps)):
                dset.overlaps[i]['raw_data1'] -= dbak.overlaps[i]['raw_data1'] * sc_factor * sc
                dset.overlaps[i]['raw_data2'] -= dbak.overlaps[i]['raw_data2'] * sc_factor * sc
                if plot_data:
                    ax.plot(dset.overlaps[i]['q_overlap'], dset.overlaps[i]['raw_data1'], "v")
                    ax.plot(dset.overlaps[i]['q_overlap'], dset.overlaps[i]['raw_data2'], "^")
        if plot_data:
            leg = ax.legend(loc='upper right', frameon=False)
            for t in leg.get_texts():
                t.set_fontsize(get_font_size(i_fs-2)[1])

        if debug==True:
            print("using scaling factor of %f" % (sc * sc_factor))
        dset.data -= dbak.data * sc * sc_factor
        dset.err += dbak.err * sc * sc_factor
        if plot_data:
            if show_eb:
                ax.errorbar(dset.qgrid, dset.data, dset.err)
            else:
                ax.plot(dset.qgrid, dset.data)

        dset.comments += "# background subtraction using the following set, scaled by %f (trans):\n" % sc
        if not sc_factor == 1.:
            dset.comments += "# with addtional scaling factor of: %f\n" % sc_factor
        dset.comments += dbak.comments.replace("# ", "## ")

        return dset

In [14]:
from py4xs.detector_config import create_det_from_attrs
import numpy as np
from py4xs.local import det_names
from py4xs.slnxs import Data1d, trans_mode
from py4xs.hdf import h5exp
from scipy.ndimage.filters import gaussian_filter
from scipy.interpolate import UnivariateSpline 
import h5py

# import os
# os.chdir('../')
# os.getcwd()

dt  = h5xs("1934_B8.h5", transField="em2_sum_all_mean_value")  # transField="em2_sum_all_mean_value"
dt.load_d1s(sn='1934_B8')
dt.set_trans(transMode=trans_mode.external)
dt.d1s['1934_B8'].keys()

de = h5exp("exp.h5")
qgrid2 = np.hstack([np.arange(0.005, 0.0499, 0.001), np.arange(0.05, 0.099, 0.002), np.arange(0.1, 3.2, 0.005)])
#dt  = h5xs("2048_B8.h5", [de.detectors, qgrid2])
#dt  = h5xs("2048_B8.h5", )  # transField="em2_sum_all_mean_value"



1934_B8
Attributes list in the constructor object []
processed attrs <KeysViewHDF5 []>
_SAXS is executing
_WAXS2 is executing
merged is executing
Finally recursion call is completed sn is 1934_B8
d1s keys  dict_keys(['_SAXS', '_WAXS2', 'merged'])
loop length  4141


In [51]:
dt.d1s['1934_B8']['merged'][10].data[:20]

array([  0.        ,   0.        , 486.29711395, 317.26634722,
       213.80951055, 147.46624926, 104.06895486,  77.06820181,
        57.78208289,  44.79722541,  34.49038235,  26.5114945 ,
        21.51251749,  17.85763242,  14.16029503,  11.67647489,
         9.90668536,   8.38696173,   7.15036163,   6.1334319 ])

In [49]:
dt.d1s['1934_B8']['merged'][10].data[:20]

array([  0.        ,   0.        , 486.29711395, 317.26634722,
       213.80951055, 147.46624926, 104.06895486,  77.06820181,
        57.78208289,  44.79722541,  34.49038235,  26.5114945 ,
        21.51251749,  17.85763242,  14.16029503,  11.67647489,
         9.90668536,   8.38696173,   7.15036163,   6.1334319 ])

In [34]:
print(dt.fh5.attrs.keys())
print(dt.attrs.keys())
print(np.isscalar('Pr'))

# testing unpack function
data = np.random.randn(5,2,3)   # --> SAXS /WAXS/merged 3721, 2, 690
print(data)
trans_value = np.zeros(len(data)) 
print(trans_value)
for i,(d,t) in enumerate(zip(data,trans_value)):
    print(f'i = {i}, d = {d}, t = {t}')

<KeysViewHDF5 ['detectors', 'qgrid', 'trans']>
dict_keys(['1934_B8'])
True
[[[ 1.15306894  0.52084053 -1.54221988]
  [-0.22893785  0.04423111 -0.11368222]]

 [[ 0.63413091  0.4111231   0.72615947]
  [ 0.3043701   1.39430244 -0.97664551]]

 [[ 1.23098884  0.24173566  1.29827319]
  [ 0.08480775 -0.17242967  0.0825077 ]]

 [[-0.75485361  0.02189807 -0.78059705]
  [-0.49986895 -0.84057312  1.69403602]]

 [[ 1.46941499 -0.08485839 -1.06355841]
  [ 1.18274751  0.06231947  0.22100816]]]
[0. 0. 0. 0. 0.]
i = 0, d = [[ 1.15306894  0.52084053 -1.54221988]
 [-0.22893785  0.04423111 -0.11368222]], t = 0.0
i = 1, d = [[ 0.63413091  0.4111231   0.72615947]
 [ 0.3043701   1.39430244 -0.97664551]], t = 0.0
i = 2, d = [[ 1.23098884  0.24173566  1.29827319]
 [ 0.08480775 -0.17242967  0.0825077 ]], t = 0.0
i = 3, d = [[-0.75485361  0.02189807 -0.78059705]
 [-0.49986895 -0.84057312  1.69403602]], t = 0.0
i = 4, d = [[ 1.46941499 -0.08485839 -1.06355841]
 [ 1.18274751  0.06231947  0.22100816]], t = 0.0


In [9]:
print(ypos[60:70])

[4.799873 4.800101 4.804741 4.804733 4.804735 4.804723 4.804719 4.804718
 4.804702 4.804711]
